# name: Download Release

# # Controls when the workflow will run
# on: push

# jobs:

  
#   get_asset:

#     runs-on: ubuntu-latest

#     steps:

#       - name: List Releases
#         run: gh release list --repo adminxeq/xeq-wallet
#         env:
#           GITHUB_TOKEN: ${{ secrets.WORKFLOW }}

#       - name: Fetch asset
#         run: gh release download --repo adminxeq/xeq-wallet v17.2.2
#         env:
#           GITHUB_TOKEN: ${{ secrets.WORKFLOW }}

#       - name: See what we downloaded
#         run: ls
        
#       - name: Upload artifacts
#         uses: actions/upload-artifact@v1
#         with:
#             name: ${{ runner.OS }}
#             path: .
            
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Build
#         run: echo ${{ github.sha }} > Release.txt
#       - name: Test
#         run: cat Release.txt
#       - name: Release
#         uses: softprops/action-gh-release@v1
#         if: startsWith(github.ref, 'refs/tags/')
#         with:
#           files: .*

name: Download Release

# Controls when the workflow will run
on: push

jobs:

  
  get_asset:

    runs-on: ubuntu-latest

    steps:

      - name: List Releases
        run: gh release list --repo adminxeq/xeq-wallet
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW }}

      - name: Fetch asset
        run: gh release download --repo adminxeq/xeq-wallet v17.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW }}

      - name: See what we downloaded
        run: ls -al
        
      - name: foo
        run: pwd
        
#       - name: Upload artifacts
#         uses: actions/upload-artifact@v1
#         with:
#             name: ${{ runner.OS }}
#             path: .
            
      - name: Publish release
        run: gh release create v17.2.2 
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW }}
